name: Build and Syntax check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Set Up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      # Restore any Dependencies
      - name: Dependencies
        run: dotnet restore

      # Run the unit test
      - name: Unit Test
        run: dotnet test

      # Build the project
      - name: Project Build
        run: dotnet build --configuration release
